name: Reolink Media Access
slug: reolink_media_access
version: "0.1.0"
description: Browse and access Reolink items exposed in Home Assistant Media Source.
url: https://example.com/addons/reolink-media-access
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386
startup: application
init: false
ingress: true
ingress_port: 8099
panel_icon: mdi:cctv
homeassistant_api: true
ports: {}
map: []
options: {}
schema: {}
image: ""
